# windows vars
wind_bootloader_src = boot\boot.asm
wind_bootloader_build = boot\boot.bin
wind_kernel_src = kernel\kernel.asm
wind_kernel_build = kernel\kernel.bin
wind_final_image = final.flp

# linux vars
lin_bootloader_src = ./boot/boot.asm
lin_bootloader_build = ./boot/boot.bin
lin_kernel_src = ./kernel/kernel.asm
lin_kernel_build = ./kernel/kernel.bin
lin_final_image = ./final.flp

# windows build functions
wind_build:
	nasm $(wind_bootloader_src) -f bin -o $(wind_bootloader_build)
	nasm $(wind_kernel_src) -f bin -o $(wind_kernel_build)
	copy /b $(wind_bootloader_build)+$(wind_kernel_build) $(wind_final_image)

wind_run:
	qemu-system-x86_64 $(wind_final_image)

wind_br : wind_build wind_run

# linux build functions
lin_build:
	nasm $(lin_bootloader_src) -f bin -o $(lin_bootloader_build)
	nasm $(lin_kernel_src) -f bin -o $(lin_kernel_build)
	cat $(lin_bootloader_build) $(lin_kernel_build) > $(lin_final_image)

lin_run:
	qemu-system-x86_64 $(lin_final_image)

lin_br : lin_build lin_run